language: python

resources:
  gpu: true

before_install:
  - sudo apt-get update
  - sudo apt-get install linux-headers-$(uname -r)
  
install: pip install gpustat

script: 
 - gpustat -cp
 - uname -r 
